# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions

# update_fastlane
fastlane_version "2.17.1"

default_platform :android

platform :android do
  before_all do
    ENV["CRASHLYTICS_API_TOKEN"] = "761dec15218ab1b985ecd5f0070f7204b59a0826"
    ENV["CRASHLYTICS_BUILD_SECRET"] = "32352c5a20c162184b4601242467a0dda1febc0e33ddf6049a1b758078c21e8e"
  end
  
  desc "Assemble"
  lane :assemble do |options|
  
  #Clean project directory
    gradle(task: "clean")
	gradle(task: 'assemble')
	
#	sign_apk(keystore_path: options[:keystore_path], input_apk_path: options[:input_apk_path],alias: options[:alias], storepass: options[:storepass], tsa: options[:tsa], signed_apk_path: options[:signed_apk_path], keypass: options[:keypass])
	
  end
  
  desc "Static Code Analysis"
  lane :static_analysis do
  
#	gradle(task: "lint checkstyle findbugs pmd")
	gradle(task: "lint")
	
  end
  
  desc "Testing"
  lane :test do

	  gradle(task: "test")

		#Generate jacoco coverage reports for release and debug
		#jacoco_gradle(build_type: "Release")
		#jacoco_gradle(build_type: "Debug")
  end
  
  desc "Nexus Upload"
  lane :nexus do 
		nexus_upload(
			file: "sample/app/build/outputs/apk/app-debug.apk",
			repo_id: "artefacts",
			repo_group_id: "com.fastlane",
			repo_project_name: "apk",
			repo_project_version: "1.13",
			repo_classifier: "dSYM", # Optional
			endpoint: "http://54.246.240.35:8081/nexus/content/repositories/snapshots/",
			username: "deployment",
			password: "n3xu5D3p"
		)
  end 
  
  desc "Publish to CRASHLYTICS"
  lane :publish do
	
#	crashlytics(
#		groups: "qa-team"
#    )
	
  end
end