#!/usr/bin/env groovy
 
/**
        * Jenkinsfile for Jenkins2 Pipeline
*/
 
import hudson.model.*
import hudson.EnvVars
import groovy.json.JsonSlurperClassic
import groovy.json.JsonBuilder
import groovy.json.JsonOutput
import java.net.URL

node {
	stage ('Checkout and Setup') {
		checkout scm
		sh 'cd sample/fastlane/'
	}
	
	stage ('Assemble') {
		sh 'cd sample/fastlane/; fastlane android assemble'
	}
	
	stage ('Lint') {
		sh 'cd sample/fastlane/; fastlane android lint'
	}
	
	stage ('Test') {
		sh 'cd sample/fastlane/; fastlane android test'
	}
	
	stage ('Crashlytics') {
		sh 'cd sample/fastlane/; fastlane android publish'
		
	}
}