#!/usr/bin/env groovy
 
/**
        * Jenkinsfile for Jenkins2 Pipeline
*/
 
import hudson.model.*
import hudson.EnvVars
import groovy.json.JsonSlurperClassic
import groovy.json.JsonBuilder
import groovy.json.JsonOutput
import java.net.URL

node {
	stage 'Checkout and Setup'
		checkout scm
		sh 'cd sample/fastlane/'
	stage 'Assemble'
		sh 'fastlane android assemble'
	stage 'Lint'
		sh 'fastlane android lint'
	stage 'Test'
		sh 'fastlane android test'
	stage 'Crashlytics'
		sh 'fastlane android publish'
}